# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "f3c38e708010aaa3be8bcdc18e3e03a6"
name = "Performance-improvement-app"
application_url = "https://shopify.dev/apps/default-app-home"
embedded = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_metaobject_definitions,write_metaobjects,write_products"

[product.metafields.app.demo_info]
type = "single_line_text_field"
name = "Demo Source Info"
description = "Tracks products created by the Shopify app template for development"

  [product.metafields.app.demo_info.access]
  admin = "merchant_read_write"

[metaobjects.app.example]
name = "Example"
description = "An example metaobject definition created by this template"

  [metaobjects.app.example.access]
  admin = "merchant_read_write"

[metaobjects.app.example.fields.title]
name = "Title"
type = "single_line_text_field"
required = true

[metaobjects.app.example.fields.description]
name = "Description"
type = "multi_line_text_field"

[metaobjects.app.script_injector_script]
name = "Script"
description = "Script injector script"

[metaobjects.app.script_injector_script.access]
admin = "merchant_read_write"

[metaobjects.app.script_injector_script.fields.name]
name = "Name"
type = "single_line_text_field"
required = true

[metaobjects.app.script_injector_script.fields.code]
name = "Code"
type = "multi_line_text_field"
required = true

[metaobjects.app.script_injector_script.fields.enabled]
name = "Enabled"
type = "boolean"
required = true

[metaobjects.app.script_injector_script.fields.target_pages]
name = "Target Pages"
type = "list.single_line_text_field"

[metaobjects.app.script_injector_script.fields.custom_page_handles]
name = "Custom Page Handles"
type = "list.single_line_text_field"

[metaobjects.app.script_injector_script.fields.position]
name = "Position"
type = "single_line_text_field"



[metaobjects.app.script_injector_script.fields.async]
name = "Async"
type = "boolean"


[metaobjects.app.script_injector_script.fields.defer]
name = "Defer"
type = "boolean"


[metaobjects.app.script_injector_config]
name = "Config"
description = "Script injector config"

[metaobjects.app.script_injector_config.access]
admin = "merchant_read_write"

[metaobjects.app.script_injector_config.fields.auto_inject]
name = "Auto Inject"
type = "boolean"


[metaobjects.app.script_injector_config.fields.debug_mode]
name = "Debug Mode"
type = "boolean"


[webhooks]
api_version = "2026-10"

  [[webhooks.subscriptions]]
  uri = "/webhooks/app/uninstalled"
  topics = [ "app/uninstalled" ]

  [[webhooks.subscriptions]]
  uri = "/webhooks/app/scopes_update"
  topics = [ "app/scopes_update" ]

[auth]
redirect_urls = [ "https://shopify.dev/apps/default-app-home/api/auth" ]

[build]
include_config_on_deploy = true
automatically_update_urls_on_dev = true
